package network.ike.plugin;

import org.apache.maven.model.Dependency;
import org.apache.maven.model.DependencyManagement;
import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugins.annotations.LifecyclePhase;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;
import org.apache.maven.project.MavenProject;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/**
 * Generate a Bill of Materials POM from another module's dependency management.
 *
 * <p>Reads the {@code <dependencyManagement>} entries from a source module
 * (default: {@code ike-parent}) in the reactor and writes a standalone BOM
 * POM with all versions resolved to literals. The generated POM replaces
 * the stub POM for install/deploy, so external consumers get a fully
 * populated BOM without any manual maintenance.</p>
 *
 * <p>Bind this goal to a POM-packaged stub module in the reactor,
 * ordered <em>after</em> the source module and the plugin module:</p>
 *
 * <pre>
 * &lt;plugin&gt;
 *   &lt;groupId&gt;network.ike&lt;/groupId&gt;
 *   &lt;artifactId&gt;ike-maven-plugin&lt;/artifactId&gt;
 *   &lt;executions&gt;
 *     &lt;execution&gt;
 *       &lt;id&gt;generate-bom&lt;/id&gt;
 *       &lt;goals&gt;&lt;goal&gt;generate-bom&lt;/goal&gt;&lt;/goals&gt;
 *     &lt;/execution&gt;
 *   &lt;/executions&gt;
 * &lt;/plugin&gt;
 * </pre>
 */
@Mojo(name = "generate-bom",
      defaultPhase = LifecyclePhase.GENERATE_RESOURCES,
      requiresProject = true,
      threadSafe = true)
public class GenerateBomMojo extends AbstractMojo {

    /** The current project (injected by Maven). */
    @Parameter(defaultValue = "${project}", readonly = true, required = true)
    private MavenProject project;

    /** Reactor projects (injected by Maven). */
    @Parameter(defaultValue = "${reactorProjects}", readonly = true, required = true)
    private List<MavenProject> reactorProjects;

    /**
     * Artifact ID of the reactor module whose {@code <dependencyManagement>}
     * entries should be copied into the generated BOM.
     */
    @Parameter(property = "bom.source", defaultValue = "ike-parent")
    private String sourceArtifactId;

    @Override
    public void execute() throws MojoExecutionException {
        // ── Find source module in reactor ────────────────────────────
        MavenProject source = reactorProjects.stream()
                .filter(p -> p.getArtifactId().equals(sourceArtifactId))
                .findFirst()
                .orElseThrow(() -> new MojoExecutionException(
                        sourceArtifactId + " not found in reactor. "
                        + "Ensure it is listed before this module in <subprojects>."));

        DependencyManagement depMgmt = source.getDependencyManagement();
        if (depMgmt == null || depMgmt.getDependencies().isEmpty()) {
            throw new MojoExecutionException(
                    sourceArtifactId + " has no <dependencyManagement> entries.");
        }

        List<Dependency> deps = depMgmt.getDependencies();

        // ── Generate BOM POM ─────────────────────────────────────────
        String bomXml = buildBomXml(deps);

        Path targetDir = Path.of(project.getBuild().getDirectory());
        try {
            Files.createDirectories(targetDir);
            Path bomPom = targetDir.resolve("generated-bom.xml");
            Files.writeString(bomPom, bomXml);

            // Replace the project POM so install/deploy uses the
            // generated BOM instead of the stub.
            project.setPomFile(bomPom.toFile());

            getLog().info("Generated BOM with " + deps.size()
                    + " managed entries from " + sourceArtifactId);
        } catch (IOException e) {
            throw new MojoExecutionException("Failed to write generated BOM", e);
        }
    }

    // ── XML generation ───────────────────────────────────────────────

    private String buildBomXml(List<Dependency> deps) {
        StringBuilder xml = new StringBuilder(4096);
        xml.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
        xml.append("<!--\n");
        xml.append("  Auto-generated BOM — do not edit.\n");
        xml.append("  Source: ").append(sourceArtifactId)
           .append(" dependencyManagement\n");
        xml.append("  Generated by: ike:generate-bom\n");
        xml.append("-->\n");
        xml.append("<project xmlns=\"http://maven.apache.org/POM/4.0.0\"\n");
        xml.append("         xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n");
        xml.append("         xsi:schemaLocation=\"http://maven.apache.org/POM/4.0.0\n");
        xml.append("         http://maven.apache.org/xsd/maven-4.0.0.xsd\">\n");
        xml.append("    <modelVersion>4.0.0</modelVersion>\n\n");

        xml.append("    <groupId>").append(project.getGroupId()).append("</groupId>\n");
        xml.append("    <artifactId>").append(project.getArtifactId()).append("</artifactId>\n");
        xml.append("    <version>").append(project.getVersion()).append("</version>\n");
        xml.append("    <packaging>pom</packaging>\n\n");

        xml.append("    <name>").append(escapeXml(project.getName())).append("</name>\n");
        if (project.getDescription() != null) {
            xml.append("    <description>")
               .append(escapeXml(project.getDescription().strip()))
               .append("</description>\n");
        }
        xml.append("    <url>").append(project.getUrl() != null ? project.getUrl() : "").append("</url>\n\n");

        // Licenses
        if (project.getLicenses() != null && !project.getLicenses().isEmpty()) {
            xml.append("    <licenses>\n");
            project.getLicenses().forEach(lic -> {
                xml.append("        <license>\n");
                xml.append("            <name>").append(escapeXml(lic.getName())).append("</name>\n");
                xml.append("            <url>").append(lic.getUrl()).append("</url>\n");
                xml.append("            <distribution>repo</distribution>\n");
                xml.append("        </license>\n");
            });
            xml.append("    </licenses>\n\n");
        }

        // Organization
        if (project.getOrganization() != null) {
            xml.append("    <organization>\n");
            xml.append("        <name>").append(escapeXml(project.getOrganization().getName())).append("</name>\n");
            xml.append("        <url>").append(project.getOrganization().getUrl()).append("</url>\n");
            xml.append("    </organization>\n\n");
        }

        // Dependency Management
        xml.append("    <dependencyManagement>\n");
        xml.append("        <dependencies>\n");

        for (Dependency dep : deps) {
            xml.append("            <dependency>\n");
            xml.append("                <groupId>").append(dep.getGroupId()).append("</groupId>\n");
            xml.append("                <artifactId>").append(dep.getArtifactId()).append("</artifactId>\n");
            xml.append("                <version>").append(dep.getVersion()).append("</version>\n");

            if (dep.getClassifier() != null && !dep.getClassifier().isEmpty()) {
                xml.append("                <classifier>").append(dep.getClassifier()).append("</classifier>\n");
            }
            if (dep.getType() != null && !"jar".equals(dep.getType())) {
                xml.append("                <type>").append(dep.getType()).append("</type>\n");
            }
            if (dep.getScope() != null && !"compile".equals(dep.getScope())) {
                xml.append("                <scope>").append(dep.getScope()).append("</scope>\n");
            }

            xml.append("            </dependency>\n");
        }

        xml.append("        </dependencies>\n");
        xml.append("    </dependencyManagement>\n");
        xml.append("</project>\n");

        return xml.toString();
    }

    private static String escapeXml(String text) {
        if (text == null) return "";
        return text.replace("&", "&amp;")
                   .replace("<", "&lt;")
                   .replace(">", "&gt;");
    }
}
