package network.ike.plugin;

import network.ike.workspace.Component;
import network.ike.workspace.WorkspaceGraph;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugins.annotations.Mojo;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/**
 * Generate Syncthing {@code .stignore} files for the workspace.
 *
 * <p>Syncthing should sync source files across a developer's own machines
 * but must NOT sync build artifacts or git metadata (those are
 * machine-specific). This goal generates two files:
 *
 * <ul>
 *   <li><b>Workspace-level {@code .stignore}</b> — ignores
 *       {@code target/}, {@code .git/}, IDE files, and OS metadata
 *       within each component directory.</li>
 *   <li><b>Per-component {@code .stignore}</b> — same patterns, placed
 *       in each cloned component for standalone Syncthing folders.</li>
 * </ul>
 *
 * <p>The generated file is deterministic (sorted, no timestamps) so
 * running the goal twice produces identical output — no Syncthing
 * churn.
 *
 * <pre>{@code mvn ike:stignore}</pre>
 */
@Mojo(name = "stignore", requiresProject = false, threadSafe = true)
public class StignoreWorkspaceMojo extends AbstractWorkspaceMojo {

    /** Standard patterns that should never be synced. */
    private static final List<String> COMMON_IGNORES = List.of(
            "// IKE Workspace .stignore",
            "// Generated by: mvn ike:stignore",
            "// Re-run after adding new components to workspace.yaml",
            "",
            "// ── Build artifacts ────────────────────────────────────",
            "**/target",
            "",
            "// ── Git metadata (each machine has its own clone) ─────",
            "**/.git",
            "",
            "// ── IDE project files ─────────────────────────────────",
            "**/.idea",
            "**/.settings",
            "**/.project",
            "**/.classpath",
            "**/*.iml",
            "**/.vscode",
            "",
            "// ── OS metadata ───────────────────────────────────────",
            ".DS_Store",
            "**/.DS_Store",
            "Thumbs.db",
            "**/Thumbs.db",
            "",
            "// ── Maven local repo + wrapper downloads ──────────────",
            "**/.mvn/local-repo",
            "**/.mvn/wrapper/maven-wrapper.jar",
            "",
            "// ── Claude Code worktrees ─────────────────────────────",
            "**/.claude/worktrees",
            "",
            "// ── Node / frontend build artifacts ──────────────────",
            "**/node_modules"
    );

    @Override
    public void execute() throws MojoExecutionException {
        WorkspaceGraph graph = loadGraph();
        File root = workspaceRoot();

        getLog().info("");
        getLog().info("IKE Workspace — Generate .stignore");
        getLog().info("══════════════════════════════════════════════════════════════");

        // Build the workspace-level .stignore
        List<String> lines = new ArrayList<>(COMMON_IGNORES);

        // Add workspace-specific ignores
        lines.add("");
        lines.add("// ── Workspace checkpoint files (git-tracked) ──────────");
        lines.add("checkpoints");

        // Write workspace .stignore
        Path workspaceStignore = root.toPath().resolve(".stignore");
        writeStignore(workspaceStignore, lines);
        getLog().info("  ✓ " + workspaceStignore);

        // Write per-component .stignore for components that are cloned
        int perComponent = 0;
        for (Component component : graph.manifest().components().values()) {
            File dir = new File(root, component.name());
            if (dir.exists()) {
                Path componentStignore = dir.toPath().resolve(".stignore");
                writeStignore(componentStignore, COMMON_IGNORES);
                perComponent++;
                getLog().info("  ✓ " + component.name() + "/.stignore");
            }
        }

        getLog().info("");
        getLog().info("  Generated: 1 workspace + " + perComponent
                + " component .stignore files");
        getLog().info("");
    }

    private void writeStignore(Path path, List<String> lines)
            throws MojoExecutionException {
        try {
            Files.writeString(path,
                    String.join("\n", lines) + "\n",
                    StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new MojoExecutionException(
                    "Failed to write " + path, e);
        }
    }
}
