package network.ike.plugin;

import network.ike.workspace.Component;
import network.ike.workspace.WorkspaceGraph;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;

/**
 * Record a workspace checkpoint — a consistent snapshot of all
 * component SHAs, branches, and versions.
 *
 * <p>Writes a YAML checkpoint file to {@code checkpoints/} in the
 * workspace root and optionally tags each component's current commit.
 *
 * <p>This is the <b>workspace-level</b> checkpoint (multi-repo).
 * For single-repo checkpoints, use {@code ike:checkpoint} instead.
 *
 * <pre>{@code
 * mvn ike:ws-checkpoint -Dname=sprint-42
 * mvn ike:ws-checkpoint -Dname=pre-release -Dtag=true
 * }</pre>
 */
@Mojo(name = "ws-checkpoint", requiresProject = false, threadSafe = true)
public class WsCheckpointMojo extends AbstractWorkspaceMojo {

    private static final DateTimeFormatter ISO_UTC =
            DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss'Z'")
                    .withZone(ZoneOffset.UTC);

    /** Checkpoint name. Used in filename and tags. Prompted if omitted. */
    @Parameter(property = "name")
    private String name;

    /** Tag each component with {@code checkpoint/<name>/<component>}. */
    @Parameter(property = "tag", defaultValue = "false")
    private boolean tag;

    /** Push tags to origin. Only applies when tag=true. */
    @Parameter(property = "push", defaultValue = "false")
    private boolean push;

    @Override
    public void execute() throws MojoExecutionException {
        name = requireParam(name, "name", "Checkpoint name");

        WorkspaceGraph graph = loadGraph();
        File root = workspaceRoot();

        String timestamp = ISO_UTC.format(Instant.now());
        String author = resolveAuthor(root);

        getLog().info("");
        getLog().info("IKE Workspace — Checkpoint");
        getLog().info("══════════════════════════════════════════════════════════════");
        getLog().info("  Name:   " + name);
        getLog().info("  Time:   " + timestamp);
        getLog().info("  Author: " + author);
        getLog().info("  Tag:    " + tag);
        getLog().info("");

        // Build checkpoint data
        List<String> yaml = new ArrayList<>();
        yaml.add("# IKE Workspace Checkpoint");
        yaml.add("# Generated by: mvn ike:ws-checkpoint -Dname=" + name);
        yaml.add("#");
        yaml.add("checkpoint:");
        yaml.add("  name: \"" + name + "\"");
        yaml.add("  created: \"" + timestamp + "\"");
        yaml.add("  author: \"" + author + "\"");
        yaml.add("  schema-version: \"" + graph.manifest().schemaVersion() + "\"");
        yaml.add("");
        yaml.add("  components:");

        int recorded = 0;
        int absent = 0;
        List<String> taggedComponents = new ArrayList<>();

        for (var entry : graph.manifest().components().entrySet()) {
            String compName = entry.getKey();
            Component component = entry.getValue();
            File dir = new File(root, compName);
            File gitDir = new File(dir, ".git");

            if (!gitDir.exists()) {
                yaml.add("    " + compName + ":");
                yaml.add("      status: absent");
                absent++;
                continue;
            }

            String sha = gitFullSha(dir);
            String shortSha = gitShortSha(dir);
            String branch = gitBranch(dir);
            String version = readVersion(dir);
            String status = gitStatus(dir);
            boolean dirty = !status.isEmpty();

            yaml.add("    " + compName + ":");
            yaml.add("      sha: \"" + sha + "\"");
            yaml.add("      short-sha: \"" + shortSha + "\"");
            yaml.add("      branch: \"" + branch + "\"");
            yaml.add("      type: " + component.type());
            if (version != null) {
                yaml.add("      version: \"" + version + "\"");
            }
            if (dirty) {
                yaml.add("      dirty: true");
                yaml.add("      # WARNING: working tree had uncommitted changes");
            }

            // Add checkpoint mechanism note
            var ct = graph.manifest().componentTypes().get(component.type());
            if (ct != null && "composite".equals(ct.checkpointMechanism())) {
                yaml.add("      # TODO: add view-coordinate from Tinkar runtime");
            }

            recorded++;

            // Tag if requested
            if (tag && !dirty) {
                String tagName = "checkpoint/" + name + "/" + compName;
                try {
                    ReleaseSupport.exec(dir, getLog(),
                            "git", "tag", tagName);
                    taggedComponents.add(compName);
                    getLog().info("  ✓ " + compName + " [" + shortSha + "] "
                            + branch + " → tagged " + tagName);
                    if (push) {
                        ReleaseSupport.exec(dir, getLog(),
                                "git", "push", "origin", tagName);
                    }
                } catch (MojoExecutionException e) {
                    getLog().warn("  ⚠ " + compName
                            + " — tag failed (may already exist): "
                            + e.getMessage());
                }
            } else {
                String dirtyMark = dirty ? " [DIRTY]" : "";
                getLog().info("  ✓ " + compName + " [" + shortSha + "] "
                        + branch + dirtyMark);
            }
        }

        // Write checkpoint file
        Path checkpointsDir = root.toPath().resolve("checkpoints");
        try {
            Files.createDirectories(checkpointsDir);
        } catch (IOException e) {
            throw new MojoExecutionException(
                    "Cannot create checkpoints directory", e);
        }

        Path checkpointFile = checkpointsDir.resolve(
                "checkpoint-" + name + ".yaml");
        try {
            Files.writeString(checkpointFile,
                    String.join("\n", yaml) + "\n",
                    StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new MojoExecutionException(
                    "Failed to write " + checkpointFile, e);
        }

        getLog().info("");
        getLog().info("  Checkpoint: " + checkpointFile);
        getLog().info("  Recorded: " + recorded + " | Absent: " + absent);
        if (tag) {
            getLog().info("  Tagged: " + taggedComponents.size()
                    + (push ? " (pushed)" : " (local only)"));
        }
        getLog().info("");
    }

    private String resolveAuthor(File root) {
        try {
            return ReleaseSupport.execCapture(root,
                    "git", "config", "user.name");
        } catch (MojoExecutionException e) {
            return System.getProperty("user.name", "unknown");
        }
    }

    private String gitFullSha(File dir) {
        try {
            return ReleaseSupport.execCapture(dir,
                    "git", "rev-parse", "HEAD");
        } catch (MojoExecutionException e) {
            return "unknown";
        }
    }

    private String readVersion(File dir) {
        try {
            return ReleaseSupport.readPomVersion(new File(dir, "pom.xml"));
        } catch (MojoExecutionException e) {
            return null;
        }
    }
}
