package network.ike.docs.koncept;

import org.asciidoctor.ast.ContentNode;
import org.asciidoctor.ast.Document;
import org.asciidoctor.ast.StructuralNode;
import org.asciidoctor.extension.InlineMacroProcessor;
import org.asciidoctor.extension.Name;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Map;
import java.util.WeakHashMap;
import java.util.concurrent.ConcurrentHashMap;

/**
 * AsciidoctorJ inline macro processor that handles {@code k:ConceptName[]}
 * syntax in AsciiDoc documents.
 * <p>
 * Usage in AsciiDoc:
 * <pre>
 * The patient presented with k:HeartFailure[] and k:AorticStenosis[].
 * A label override: k:HeartFailure[Congestive Heart Failure].
 * </pre>
 * <p>
 * Each reference renders as a clickable SVG badge linking to the
 * koncept's glossary entry, which is auto-generated by
 * {@link KonceptGlossaryProcessor}.
 * <p>
 * All referenced koncepts are collected in a document-scoped registry
 * for deduplication and glossary generation.
 */
@Name("k")
public class KonceptInlineMacro extends InlineMacroProcessor {

    private static final Logger LOG = LoggerFactory.getLogger(KonceptInlineMacro.class);

    /**
     * Static registry keyed by Document identity. Uses WeakHashMap so entries
     * are garbage-collected when the Document is no longer referenced.
     * AsciidoctorJ 3.0 does not preserve Java objects in document attributes,
     * so a static map is used for inter-extension communication.
     */
    private static final Map<Document, Map<String, KonceptEntry>> REGISTRIES =
            new WeakHashMap<>();

    @Override
    public Object process(ContentNode parent, String target, Map<String, Object> attributes) {
        Document doc = ((StructuralNode) parent).getDocument();
        Map<String, KonceptEntry> registry = getOrCreateRegistry(doc);

        // Register this reference (idempotent on first occurrence)
        registry.computeIfAbsent(target, KonceptEntry::new)
                .incrementRefCount();

        LOG.debug("Koncept reference: {} (total refs: {})",
                target, registry.get(target).getRefCount());

        // Determine display label
        // Positional attribute 1 is the content inside brackets: k:Target[label]
        String label = resolveLabel(target, attributes);

        // Backend-aware rendering
        String backend = doc.getAttribute("backend", "html5").toString();
        String rendered;
        if ("docbook5".equals(backend) || "docbook".equals(backend)) {
            // Plain text passthrough for DocBook — styled by XSL template
            rendered = "<phrase role=\"koncept\">K[" + escapeXml(label) + "]</phrase>";
        } else if ("pdf".equals(backend)) {
            // Prawn PDF: only basic HTML elements are supported (no SVG).
            // Use <strong> + <code> for a styled inline reference.
            rendered = "<strong><font color=\"#2a5a8a\">K</font></strong>"
                    + "<code>" + escapeXml(label) + "</code>";
        } else {
            // SVG badge for html5 and CSS-based PDF backends (Prince, AH, WeasyPrint)
            rendered = KonceptSvgRenderer.render(target, label);
        }

        // Return as inline passthrough (no further substitution)
        return createPhraseNode(parent, "quoted", rendered,
                Map.of("subs", ":none"));
    }

    private String escapeXml(String s) {
        if (s == null) return "";
        return s.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\"", "&quot;");
    }

    /**
     * Resolve the display label for this koncept reference.
     * Priority: explicit bracket content > camelCase split of target.
     */
    private String resolveLabel(String target, Map<String, Object> attributes) {
        Object explicit = attributes.get("1");
        if (explicit != null && !explicit.toString().isBlank()) {
            return explicit.toString().strip();
        }
        return splitCamelCase(target);
    }

    /**
     * Split a CamelCase identifier into space-separated words.
     * "HeartFailure" → "Heart Failure"
     * "AcuteMyocardialInfarction" → "Acute Myocardial Infarction"
     */
    static String splitCamelCase(String s) {
        return s.replaceAll("([a-z])([A-Z])", "$1 $2")
                .replaceAll("([A-Z]+)([A-Z][a-z])", "$1 $2");
    }

    /**
     * Get or lazily create the document-scoped koncept registry.
     */
    static synchronized Map<String, KonceptEntry> getOrCreateRegistry(Document doc) {
        return REGISTRIES.computeIfAbsent(doc, d -> new ConcurrentHashMap<>());
    }

    /**
     * Retrieve the registry for a given document, or null if none exists.
     */
    static synchronized Map<String, KonceptEntry> getRegistry(Document doc) {
        return REGISTRIES.get(doc);
    }

    /**
     * Remove and return the registry for a given document.
     * Called by the postprocessor after consuming the registry to prevent
     * stale entries accumulating across conversions.
     */
    static synchronized Map<String, KonceptEntry> removeRegistry(Document doc) {
        return REGISTRIES.remove(doc);
    }

}
